import { ExpenseCategory, CategoryMetadata } from '../types/index.js';

export const CATEGORIES_DATA: Record<ExpenseCategory, CategoryMetadata> = {
  [ExpenseCategory.FOOD_DINING]: {
    id: ExpenseCategory.FOOD_DINING,
    name: 'Food & Dining',
    icon: 'Utensils',
    color: '#f97316',
    badgeBg: 'bg-orange-500/10 text-orange-500 dark:text-orange-400 border-orange-500/20',
    badgeText: 'text-orange-500',
  },
  [ExpenseCategory.TRANSPORT]: {
    id: ExpenseCategory.TRANSPORT,
    name: 'Transport',
    icon: 'Car',
    color: '#0ea5e9',
    badgeBg: 'bg-sky-500/10 text-sky-500 dark:text-sky-400 border-sky-500/20',
    badgeText: 'text-sky-500',
  },
  [ExpenseCategory.SHOPPING]: {
    id: ExpenseCategory.SHOPPING,
    name: 'Shopping',
    icon: 'ShoppingBag',
    color: '#a855f7',
    badgeBg: 'bg-purple-500/10 text-purple-500 dark:text-purple-400 border-purple-500/20',
    badgeText: 'text-purple-500',
  },
  [ExpenseCategory.RENT]: {
    id: ExpenseCategory.RENT,
    name: 'Rent',
    icon: 'Home',
    color: '#6366f1',
    badgeBg: 'bg-indigo-500/10 text-indigo-500 dark:text-indigo-400 border-indigo-500/20',
    badgeText: 'text-indigo-500',
  },
  [ExpenseCategory.BILLS]: {
    id: ExpenseCategory.BILLS,
    name: 'Bills',
    icon: 'Zap',
    color: '#eab308',
    badgeBg: 'bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/20',
    badgeText: 'text-yellow-500',
  },
  [ExpenseCategory.GROCERIES]: {
    id: ExpenseCategory.GROCERIES,
    name: 'Groceries',
    icon: 'ShoppingCart',
    color: '#10b981',
    badgeBg: 'bg-emerald-500/10 text-emerald-500 dark:text-emerald-400 border-emerald-500/20',
    badgeText: 'text-emerald-500',
  },
  [ExpenseCategory.ENTERTAINMENT]: {
    id: ExpenseCategory.ENTERTAINMENT,
    name: 'Entertainment',
    icon: 'Film',
    color: '#ec4899',
    badgeBg: 'bg-pink-500/10 text-pink-500 dark:text-pink-400 border-pink-500/20',
    badgeText: 'text-pink-500',
  },
  [ExpenseCategory.HEALTH]: {
    id: ExpenseCategory.HEALTH,
    name: 'Health',
    icon: 'HeartPulse',
    color: '#f43f5e',
    badgeBg: 'bg-rose-500/10 text-rose-500 dark:text-rose-400 border-rose-500/20',
    badgeText: 'text-rose-500',
  },
  [ExpenseCategory.EDUCATION]: {
    id: ExpenseCategory.EDUCATION,
    name: 'Education',
    icon: 'BookOpen',
    color: '#06b6d4',
    badgeBg: 'bg-cyan-500/10 text-cyan-500 dark:text-cyan-400 border-cyan-500/20',
    badgeText: 'text-cyan-500',
  },
  [ExpenseCategory.TRAVEL]: {
    id: ExpenseCategory.TRAVEL,
    name: 'Travel',
    icon: 'Plane',
    color: '#14b8a6',
    badgeBg: 'bg-teal-500/10 text-teal-500 dark:text-teal-400 border-teal-500/20',
    badgeText: 'text-teal-500',
  },
  [ExpenseCategory.OTHERS]: {
    id: ExpenseCategory.OTHERS,
    name: 'Others',
    icon: 'Package',
    color: '#64748b',
    badgeBg: 'bg-slate-500/10 text-slate-500 dark:text-slate-400 border-slate-500/20',
    badgeText: 'text-slate-500',
  },
};

export const CATEGORY_OPTIONS = Object.values(ExpenseCategory);
